# Generated by Django 5.1.3 on 2025-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact number for this product (optional)', max_length=15, null=True),
        ),
    ]
