# Generated by Django 5.1.3 on 2025-03-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name': 'Product Rating', 'verbose_name_plural': 'Product Ratings'},
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user')},
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='created_at',
        ),
    ]
