# Generated by Django 5.1.3 on 2024-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(default=250789232324, max_length=255),
            preserve_default=False,
        ),
    ]
