# Generated by Django 5.1.3 on 2025-04-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productrating_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'ordering': ['id'], 'verbose_name': 'Product Rating', 'verbose_name_plural': 'Product Ratings'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['id']},
        ),
    ]
