# Generated by Django 5.1.3 on 2024-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(max_length=25),
        ),
    ]
