# Generated by Django 5.1.3 on 2025-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='Profile picture (optional)', null=True, upload_to='avatars/'),
        ),
    ]
