# Generated by Django 5.1.3 on 2025-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_latitude_product_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact number for this product (optional)', max_length=10, null=True),
        ),
    ]
