# Generated by Django 5.1.3 on 2025-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='intent',
            field=models.CharField(default=('Hello',), max_length=50),
            preserve_default=False,
        ),
    ]
