# Generated by Django 5.1.3 on 2024-12-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_unit_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('umuhinzi', 'Umuhinzi'), ('umuguzi', 'Umuguzi'), ('cooperative', 'Cooperative')], max_length=15, null=True),
        ),
    ]
