# Generated by Django 5.1.3 on 2025-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='intent',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
