# Generated by Django 5.1.3 on 2025-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('cooperative', 'Cooperative')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('cooperative', 'Cooperative')], max_length=15, null=True),
        ),
    ]
