# Generated by Django 5.1.3 on 2025-02-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatroom_message_notification_privateconversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='privateconversation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='privateconversation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='privateconversation',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='privateconversation',
            name='user2',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PrivateConversation',
        ),
    ]
