# Generated by Django 5.1.3 on 2025-05-02 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_rwanda_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='core.cell'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='core.district'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='core.province'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='core.sector'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Additional location details (e.g., office number, landmark)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='core.village'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.cell'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.district'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.province'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.sector'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Additional location details (e.g., house number, landmark)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.village'),
        ),
    ]
