# Generated by Django 5.1.3 on 2025-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_role_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('umuhinzi', 'Umuhinzi'), ('umuguzi', 'Umuguzi'), ('cooperative', 'Cooperative')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('umuhinzi', 'Umuhinzi'), ('umuguzi', 'Umuguzi'), ('cooperative', 'Cooperative')], max_length=15, null=True),
        ),
    ]
