# Generated by Django 5.1.3 on 2025-02-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_message_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
