# Generated by Django 5.1.3 on 2025-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_populate_cells_villages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, help_text='Upload an image (jpg, png) or video (mp4)', null=True, upload_to='products/'),
        ),
    ]
