# Generated by Django 5.1.3 on 2025-05-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_rwanda_locations'),
        ('core', '0011_remove_product_image_alter_product_media'),
    ]

    operations = [
    ]
