# Generated by Django 5.1.3 on 2025-03-05 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_price_per_unit_productrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
