# Generated by Django 5.1.3 on 2025-05-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250505_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact',
        ),
    ]
