# Generated by Django 5.1.3 on 2025-05-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='longitude',
        ),
    ]
